{{- if .Values.ingress.enabled -}}
{{- $fullName := include "backend-service.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "backend-service.name" . }}
    chart: {{ template "backend-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: gce
#    kubernetes.io/ingress.global-static-ip-name: swagger-static-ip
#    networking.gke.io/managed-certificates: swagger
spec:
  backend:
    serviceName: spectacle-service
    servicePort: 8080

{{- end }}
